Enabling github action tests
openethereum/openethereum pull request #255
Opened 2021-02-04 11:59 UTC by rakita

When removing windows build we removed test execution, reverting this change.

2021-02-04 21:30 UTC, adria0 requested changes
As far as I see this is going to change some JSON-RPC responses? This is a breaking change for clients, and JSON codification for typed tx ids and access lists will be defined sooner in another EIP.

2021-02-05 08:06 UTC, rakita commented
Other clients already enabled eip2718 in their RPC. This is example from Geth: https://github.com/ethereum/go-ethereum/pull/21502#issuecomment-758659399 
But I will need to change how we present accessList address/key in json.

2021-02-05 08:10 UTC, rakita commented
and i will see to update our wiki

2021-02-05 18:20 UTC, adria0 commented on crates/rpc/src/v1/types/transaction_request.rs
> +    pub access_list: Option<Vec<AccessListItem>>,
```suggestion
    pub access_list: Option<AccessList>,
```

2021-02-05 18:21 UTC, adria0 commented on crates/rpc/src/v1/types/transaction.rs
> +    pub access_list: Option<Vec<AccessListItem>>,
```suggestion
    pub access_list: Option<AccessList>,
```

2021-02-05 18:22 UTC, adria0 commented on crates/rpc/src/v1/types/call_request.rs
> +    pub access_list: Option<Vec<AccessListItem>>,
```suggestion
    pub access_list: Option<AccessList>,
```

2021-02-05 18:22 UTC, adria0 commented on crates/rpc/src/v1/helpers/requests.rs
> +    pub access_list: Option<Vec<AccessListItem>>,
```suggestion
    pub access_list: Option<AccessList>,
```

2021-02-08 13:54 UTC, adria0 approved these changes

2021-02-08 13:54 UTC, karim-agha approved these changes

2021-02-08 13:55 UTC, merged